---
- name: Listen for ManagedCluster across
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: "cluster.open-cluster-management.io/v1"
        kind: ManagedCluster
        api_key: "{{ vault_api_key }}"
        label_selectors:
          - type=eda
  rules:
    - name: Start Managed Clusters Day2 Automation (Workflow Only)
      enabled: false
      condition: event.type == "ADDED"
#        all:
#          - event.type == "ADDED"
## Make sure ACM Managed Imported cluster condition are True
#          - event.resource.status.conditions[0].status == True
#          - event.resource.status.conditions[1].status == True
#          - event.resource.status.conditions[2].status == True
#          - event.resource.status.conditions[3].status == True
#          - event.resource.status.conditions[4].status == True
# Make sure ACM Managed Imported cluster has installed addon-managed-serviceaccount
#          - event.resource.metadata.labels.feature.open-cluster-management.io/addon-managed-serviceaccount == "available"
      actions:
        - print_event:
            pretty: true
        - debug:
            msg: "Run Workflow"
...
