---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  ## Define the conditions we are looking for

  rules:
    - name: R1 - Heard "Hello!"
      condition: event.payload.message == "Hello!"
      action:
        debug:
          msg: "You said, '{{ event.payload.message }}'. Is it me you're looking for?"

    - name: R2 - Didn't hear "Hello!"
      condition: event.payload.message is defined and event.payload.message != "Hello!"
      action:
        debug:
          msg: "You said, '{{ event.payload.message }}'. Is that what you meant to say?"
