---
- name: Listen for events on a webhook
  hosts: all

 ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

 ## Define the conditions we are looking for

  rules:
    - name: Telegram message for team01
      condition: event.payload.message == "team01"
      action:
        run_job_template:
          name: "Send Telegram"
          organization: Default
          job_args:
            extra_vars:
               team_name: team01

    - name: Telegram message for team02
      condition: event.payload.message == "team02"
      action:
        run_job_template:
          name: "Send Telegram"
          organization: Default
          job_args:
            extra_vars:
               team_name: team02

    - name: Telegram message for team03
      condition: event.payload.message == "team03"
      action:
        run_job_template:
          name: "Send Telegram"
          organization: Default
          job_args:
            extra_vars:
               team_name: team03

    - name: Telegram message for team04
      condition: event.payload.message == "team04"
      action:
        run_job_template:
          name: "Send Telegram"
          organization: Default
          job_args:
            extra_vars:
               team_name: team04

    - name: Telegram message for team05
      condition: event.payload.message == "team05"
      action:
        run_job_template:
          name: "Send Telegram"
          organization: Default
          job_args:
            extra_vars:
               team_name: team05
...
