---
- name: Listen for events on a webhook
  hosts: all

 ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

 ## Define the conditions we are looking for

  rules:
    - name: Telegram message for team01
      condition: event.payload.message == "team01quarkus"
      actions:
        - run_job_template:
            name: "Send Telegram"
            organization: Default
            job_args:
              extra_vars:
                 team_name: team01

    - name: Telegram message for team02
      condition: event.payload.message == "team02ansible"
      action:
        run_job_template:
          name: "Send Telegram"
          organization: Default
          job_args:
            extra_vars:
               team_name: team02

    - name: Telegram message for team03
      condition: event.payload.message == "team03tekton"
      action:
        run_job_template:
          name: "Send Telegram"
          organization: Default
          job_args:
            extra_vars:
               team_name: team03

    - name: Telegram message for team04
      condition: event.payload.message == "team04argo"
      action:
        run_job_template:
          name: "Send Telegram"
          organization: Default
          job_args:
            extra_vars:
               team_name: team04

    - name: Telegram message for team05
      condition: event.payload.message == "team05podman"
      action:
        run_job_template:
          name: "Send Telegram"
          organization: Default
          job_args:
            extra_vars:
               team_name: team05
...
