---
- name: Send telegram message
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/vault.yml
  vars:
    gymkanaGroups:
      team01:
        chatID: "-965962147"
        msgVar: "Team: team01; URL: https://{{ controller_hostname }}; User: team01; Password: {{ pass_team01 }}"
      team02:
        chatID: "-986132187"
        msgVar: "Team: team02; URL: https://{{ controller_hostname }}; User: team02; Password: {{ pass_team02 }}"
      team03:
        chatID: "-842460734"
        msgVar: "Team: team03; URL: https://{{ controller_hostname }}; User: team03; Password: {{ pass_team03 }}"
      team04:
        chatID: "-928100725"
        msgVar: "Team: team04; URL: https://{{ controller_hostname }}; User: team04; Password: {{ pass_team04 }}"
      team05:
        chatID: "-942244898"
        msgVar: "Team: team05; URL: https://{{ controller_hostname }}; User: team05; Password: {{ pass_team05 }}"

  tasks:

    - name: Sending message
      ansible.builtin.uri:
        url: "https://api.telegram.org/bot{{ tokenBot }}/sendmessage?chat_id={{ gymkanaGroups[team_name]['chatID'] }}&parse_mode=HTML&text={{ gymkanaGroups[team_name]['msgVar'] | urlencode }}"
...
