- name: Send telegram message
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yml
  vars:
    gymkanaGroups:
      team01:
        chatID: "-965962147"
        msgVar: "Team: team01; URL: https://controller; User: test1; Password: test"
      team02:
        chatID: "-986132187"
        msgVar: "Team: team02; URL: https://controller; User: test2; Password: test"
      team03:
        chatID: "-842460734"
        msgVar: "Team: team03; URL: https://controller; User: test3; Password: test"
      team04:
        chatID: "-928100725"
        msgVar: "Team: team04; URL: https://controller; User: test4; Password: test"
      team05:
        chatID: "-942244898"
        msgVar: "Team: team05; URL: https://controller; User: test5; Password: test"

  tasks:

    - name: Sending message
      ansible.builtin.uri:
      var:
        url: "https://api.telegram.org/bot{{ tokenBot }}/sendmessage?chat_id={{ gymkanaGroups[team_name]['chatID'] }}&parse_mode=HTML&text={{ gymkanaGroups[team_name]['msgVar'] }}"
